name: avalinks
description: Avalinks

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.3+1

  font_awesome_flutter: ^8.4.0
  html_unescape: ^1.0.1+3
  flutter_html: ^0.10.4
  grouped_buttons: ^1.0.4
  webview_flutter: ^0.3.14+1

  regexed_validator: ^1.0.2

  progress_dialog: ^1.1.0+1

  file_picker: ^1.3.7
  url_launcher: ^5.0.3

  dio: ^2.1.7
  cached_network_image: ^2.0.0
  json_annotation: ^3.0.0

  firebase_admob: ^0.9.0+7
  google_sign_in: ^4.0.4
  flutter_facebook_login: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.6.7
  json_serializable: ^3.2.2
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/img_splash_bg.jpg
    - images/icon_app_logo.png
    - images/icon_google_plus.png
    - images/icon_facebook.png
    - images/icon_forgot_pass.png
    - images/icon_service.png
    - images/icon_blog.png
    - images/icon_subscription.png
    - images/icon_profile.png
    - images/icon_change_password.png
    - images/icon_logout.png
    - images/nodata.png

  fonts:
    - family: AvenirNext
      fonts:
        - asset: fonts/avenir_next.ttf
