name: gcuf
description: A new Flutter application.

 
publish_to: "none" # Remove this line if you wish to publish to pub.dev

 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^1.1.1
  serial_number: ^0.1.0
  google_sign_in: ^4.4.4
  uuid: ^2.0.4
  local_auth: ^0.4.0+1
  google_fonts: ^1.0.0
  flutter_speed_dial: ^1.2.5
  progress_dialog: ^1.2.1
  flutter_spinkit: "^4.1.2"
  geolocator: ^5.3.1
  image_cropper: ^1.2.1
  photo_view: ^0.9.2
  intl: ^0.15.1
  google_maps_flutter: ^0.5.27
  image_picker: 0.6.0+17
  firebase_auth: ^0.15.5+3
  firebase_core: ^0.4.2+1
  cloud_firestore: ^0.12.11
  firebase_storage: ^3.1.5
  flutter_advanced_networkimage: any
  firebase_database: ^3.1.3
  curved_navigation_bar: ^0.3.2
  flutter_staggered_grid_view: "^0.3.0"
  flutter_slidable: "^0.5.4"
  flutter_circular_chart: ^0.1.0
  percent_indicator: "^2.1.1"
  provider: ^4.1.2
  font_awesome_flutter: ^8.5.0
  http: ^0.12.0+1
  json_serializable: ^2.0.2
  cached_network_image: ^2.0.0
  location: ^2.3.5
  flutter_polyline_points: ^0.1.0
  carousel_slider: ^1.4.1
  page_transition: "^1.1.5"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
#   flutter_launcher_icons: ^0.7.2
# flutter_icons:
#   android: true
#   ios: true
#   image_path: "images/person.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/dsa.jpg
    - images/person.jpg
    - images/search.gif
    - images/applogo.png
    - images/code.png
    - images/Search1.gif
   
